
services:
  db:
    image: postgres:latest
    restart: always
    tty: true
    volumes:
      - .docker/PostgreSQL:/var/lib/postgresql/data
    ports:
      - 5432:5432
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seletivo
    networks:
      - mynetwork
  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 10;
        mc alias set myminio http://minio:9000 admin123 strongpassword123;
        mc ls myminio/fotos || mc mb myminio/fotos;
        mc policy set public myminio/fotos;
      "
    networks:
      - mynetwork
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ROOT_USER: admin123
      MINIO_ROOT_PASSWORD: strongpassword123
#      MINIO_BROWSER_REDIRECT_URL: http://localhost:9003
#      MINIO_SERVER_URL :  http://minio:9000
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - .docker/minio:/data
    command:  minio server /data  --console-address ':9001'
    restart: always
    networks:
      - mynetwork

  api:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: api-processo-seletivo
    restart: always
    ports:
      - "8083:8083"
    environment:
      DB_URL: db:5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_SCHEMA: seletivo
      S3_URL: http://minio:9000
      S3_URL_PUBLIC: http://localhost:9003/minio
      S3_ACCESS_KEY: admin123
      S3_ACCESS_SECRET: strongpassword123
      S3_BUCKET_NAME: fotos
      JWT_EXPIRATION_ACCES_TOKEN: 300000
      JWT_EXPIRATION_REFRESH_TOKEN: 86400000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - mynetwork
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "9003:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio
    restart: always
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge
