INSERT INTO public.cidade (cid_nome, cid_uf) VALUES
('Fortaleza', 'CE'),
('Recife', 'PE'),
('Brasília', 'DF'),
('Manaus', 'AM'),
('Porto Alegre', 'RS'),
('Campinas', 'SP'),
('São Luís', 'MA'),
('Belém', 'PA'),
('Goiânia', 'GO'),
('Natal', 'RN'),
('Maceió', 'AL'),
('Teresina', 'PI'),
('Cuiabá', 'MT'),
('João Pessoa', 'PB'),
('Aracaju', 'SE');